# Generated by Django 5.1.6 on 2026-09-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('breadcrumb', models.JSONField(blank=True, default=list)),
                ('raw_category', models.CharField(blank=True, max_length=200)),
                ('price_low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='CLP', max_length=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('rating_value', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('rating_count', models.PositiveIntegerField(blank=True, null=True)),
                ('extraction_method', models.CharField(blank=True, max_length=30)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('component_type', models.CharField(choices=[('prebuilt_pc', 'PC Armado'), ('notebook', 'Notebook'), ('cpu', 'Procesador'), ('motherboard', 'Placa Madre'), ('ram', 'Memoria RAM'), ('gpu', 'Tarjeta de Video'), ('psu', 'Fuente de Poder'), ('case', 'Gabinete'), ('cooler', 'Refrigeracion'), ('storage', 'Almacenamiento'), ('monitor', 'Monitor'), ('peripheral', 'Accesorio/Periferico'), ('service', 'Servicio'), ('other', 'Otro')], db_index=True, default='other', max_length=20)),
                ('specs', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
